# screen
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
VIRTUAL_SCREEN_WIDTH = SCREEN_WIDTH // 2
VIRTUAL_SCREEN_HEIGHT = SCREEN_HEIGHT // 2

TILESIZE = 32

# overlay positions
OVERLAY_POSITIONS = {
    'tool': (40, SCREEN_HEIGHT - 15)
}

# layers
LAYERS = {
    'ground': 0,
    'main': 1
}

# colours
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

# time
SECOND_TO_MILLISECOND = 1000
