# screen
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
VIRTUAL_SCREEN_WIDTH = SCREEN_WIDTH / 3
VIRTUAL_SCREEN_HEIGHT = SCREEN_HEIGHT / 3

TILESIZE = 32

# overlay positions
OVERLAY_POSITIONS = {
    'tool': (40, SCREEN_HEIGHT - 15)
}

LAYERS = {
    'ground': 0,
    'main': 1
}
